planners:
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: DWAPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 2.0

oscillation_timeout: 5.0
oscillation_distance: 0.2

# planners:
#   - name: NavfnROS
#     type: navfn/NavfnROS